### ISSUE TITLE
Questions et réflexions

### ISSUE THREAD

**Issue by johanricher** [Delegation-numerique-en-sante/covid19-algorithme-orientation-schema-donnees#2]
Bonjour Mauko, je découvre le projet à l'instant et pose ici mes premières réactions à chaud, ne sois pas surpris si elles contiennent des erreurs dues à ma compréhension plutôt superficielle : 

Concernant la source de ces données :
- Comment et par qui sont produites les données qui ont vocation à être conforme à ce schéma ?
- Est-ce tu peux partager des exemples de fichiers tel qu'ils sont produits dans leur contexte d'origine ? (output brut)

Concernant le traitement de ces données :
- Est-ce que la chaîne devra être entièrement automatisée ? 
- Comment est-il prévu de valider ces données ? 
- Est-ce qu'un outil d'aide pour des humains est prévu ? 

Si un outillage orienté utilisateur final est envisagé, il peut être pertinent de s'appuyer sur ce qui existe déjà.
De même, si les données sont produites via la saisie de données par des humains, il serait à mon sens également pertinent de valider les données _dès_ cette saisie ou collecte de données, afin d'éviter le maximum d'erreurs.

Pour info, j'ai participé avec mon équipe à @jailbreak-paris au projet [Validata](https://go.validata.fr/) porté par OpenDataFrance, qui a ensuite débouché sur le lancement de [schema.data.gouv.fr](https://schema.data.gouv.fr/) avec notamment @AntoineAugusti et @abulte aux manettes.
@pajachiet a également sa propre expérience qu'il pourrait partager sur le sujet avec le Health Data Hub et la [Documentation du SNDS](https://documentation-snds.health-data-hub.fr/).

En lien avec tout ça, il existe différents outils qui, si les hypothèses ci-dessus correspondent aux besoins de ton projet, pourraient t'être utiles : 
- Pour écrire un schéma : [Table Schema](https://specs.frictionlessdata.io/table-schema/)
- Pour valider si un fichier est conforme au schéma : [GoodTables](https://next.frictionlessdata.io/tooling/goodtables/), [Validata](https://git.opendatafrance.net/validata/)
- Pour saisir un fichier conforme au schéma : [csv-gg](https://github.com/etalab/csv-gg)
- Pour documenter un schéma : [Table Schema to Markdown](https://www.npmjs.com/package/@opendataschema/table-schema-to-markdown)

**Comment by bzg** [comment]
Salut @johanricher - merci pour ton retour.  Ci-dessous quelques éléments de réponse.

D'abord un historique rapide:

- https://maladiecoronavirus.fr a été lancé
- Ils sont dès le début en discussion avec l'institut Pasteur
- Un comité s'est monté - CovidTélé - avec le ministère de la Santé autour de l'institut Pasteur pour définir les données utiles à collecter dans le cadre de ce test d'auto-évaluation
- Le Délégation Numérique en Santé (du ministère des Solidarités et de la Santé) a publié une [documentation](https://github.com/Delegation-numerique-en-sante/covid19-algorithme-orientation) qui couvre plusieurs aspects du test, définissant à la fois les questions, les réponses, l'algorithme calculant le message d'orientation, les [variables et leurs valeurs acceptables](https://github.com/Delegation-numerique-en-sante/covid19-algorithme-orientation/blob/master/implementation.org#variables-%C3%A0-obligatoirement-sauvegarder-pour-partage) que chaque structure doit respecter si elle veut être en mesure de partager ses données avec CovidTélé
- @maukoquiroga a développé une API en Elixir [dans ce dépôt](https://github.com/Delegation-numerique-en-sante/covid19-algorithme-orientation-elixir)
- ... et produit les spécifications OpenAPI depuis ce dépôt de l'API (en "bonus")
- ... puis créé ce dépôt `covid19-algorithme-orientation-schema-donnees` pour référencer ces spécifications

> Comment et par qui sont produites les données qui ont vocation à être conforme à ce schéma ?

Toute "structure" (administration, entreprise, association ou même individu) souhaitant implémenter le test d'auto-évaluation est invitée à respecter la [documentation](https://github.com/Delegation-numerique-en-sante/covid19-algorithme-orientation).

Tout structure souhaitant à la fois collecter de la donnée et la partager avec CovidTélé est invitée à respecter le schéma de données.

> Est-ce tu peux partager des exemples de fichiers tel qu'ils sont produits dans leur contexte d'origine ? (output brut)

Voir [cette section](https://github.com/Delegation-numerique-en-sante/covid19-algorithme-orientation/blob/master/exemples.org#exemple-de-fichier-csv-avec-les-donn%C3%A9es) de la documentation.

> Est-ce que la chaîne devra être entièrement automatisée ?

Chaque structure est responsable de sa chaîne de traitement de données.

> Comment est-il prévu de valider ces données ?

L'institut Pasteur collectera les données des structures référencées et procédera à leur validation. Dans le cas où les données sont publiables en open data, tous les moyens pour valider les données sont envisageables.

> Si un outillage orienté utilisateur final est envisagé, il peut être pertinent de s'appuyer sur ce qui existe déjà.

Oui - toute aide est la bienvenue pour ça!

> De même, si les données sont produites via la saisie de données par des humains, il serait à mon sens également pertinent de valider les données dès cette saisie ou collecte de données, afin d'éviter le maximum d'erreurs.

N'hésite pas à proposer des évolutions de la [documentation](https://github.com/Delegation-numerique-en-sante/covid19-algorithme-orientation/) pour aider les entités à faire cette validation en amont et à s'approprier les outils existants pour la validation de leurs données.

> En lien avec tout ça, il existe différents outils qui, si les hypothèses ci-dessus correspondent aux besoins de ton projet, pourraient t'être utiles :

Oui, on a de quoi documenter et accompagner encore mieux. Nous serons pris par des urgences d'ici demain, mais n'hésite pas à faire des propositions. Merci !

**Comment by bonjourmauko** [comment]
Merci @bzg et @johanricher !

Juste en complément effectivement deux moments de validation de la donnée :

* Pendant la saisie, à la source donc
* Au moment de la remonter, en étude

Jusqu'à hier c'était l'API elle même qui faisait une validation stricte du schéma de données (refus des données pas accordes au schéma, incomplètes, ou avec les mauvais valeurs).

Aujourd'hui on fait confiance aux structures (clients), or il n'est pas écarté qu'on fasse une validation _ex _post_.

Je ne vais pas hésiter à te contacter si l'on avance sur cette piste.

**Comment by bzg** [comment]
J'ai produit un [schéma de données](https://github.com/Delegation-numerique-en-sante/covid19-algorithme-orientation-check/blob/master/schema.json) TableSchema pour les données des questionnaires d'orientation qui respectent [la documentation](https://delegation-numerique-en-sante.github.io/covid19-algorithme-orientation/).

Il est en cours de référencement sur [schema.data.gouv.fr](https://github.com/etalab/schema.data.gouv.fr/pull/99).

Je pense que ce dépôt (`https://github.com/Delegation-numerique-en-sante/covid19-algorithme-orientation-schema-donnees/`) peut être supprimé pour éviter la confusion - le schéma OpenAPI utilisé par l'API déployée pour le [questionnaire d'orientation du SIG](https://www.gouvernement.fr/info-coronavirus/orientation-medicale) étant par ailleurs disponible dans [le dépôt de l'API](https://github.com/Delegation-numerique-en-sante/covid19-algorithme-orientation-api/).

**Comment by johanricher** [comment]
Merci pour toutes ces infos !
