### ISSUE TITLE
Supprimer (ou renommer et archiver?) le dépôt 

### ISSUE THREAD

**Issue by bzg** [Delegation-numerique-en-sante/covid19-algorithme-orientation-schema-donnees#7]
Ce dépôt contient un schéma OpenAPI qui correspond à l'implémentation de l'[API](https://github.com/Delegation-numerique-en-sante/covid19-algorithme-orientation-api/).

Un schéma de données TableSchema est disponible sur [cet autre dépôt](https://github.com/Delegation-numerique-en-sante/covid19-algorithme-orientation-check/).

Je propose de supprimer ou de renommer et archiver ce dépôt pour éviter toute confusion.

@maukoquiroga WDYT?

**Comment by bzg** [comment]
Salut @maukoquiroga - OK pour que je supprime ce dépôt ?

**Comment by bonjourmauko** [comment]
Si l'objectif est que d'autres puissent boostrapper leurs API, je dirais 
renommer sans archiver.

Par exemple covid19-algorithme-orientation-openapi

Bastien a écrit le 20/04/2020 à 08:24 :

**Comment by bzg** [comment]
> covid19-algorithme-orientation-openapi

Oui, ça me paraît bien. Je peux le faire si tu veux. Merci !

**Comment by bonjourmauko** [comment]
Done !

**Comment by bzg** [comment]
Merci !
